### ISSUE TITLE
Adding Hotkeys Feature

### ISSUE THREAD

**Issue by hansal7014** [kartik-budhiraja/Notify#1]
## Feature Description

It would be good to have the "CTRL + S" keyboard shortcut for the convenience of the end users.

## Feature Scope

This enhancement would allow the users to use the ubiquitous keyboard shortcut "CTRL + S" to save their work and will prevent the default pop-up from appearing.

**Comment by hansal7014** [comment]
Hi @kartik-budhiraja ,
Can I start working on this feature?
Thanks.

**Comment by kartik-budhiraja** [comment]
@hansal7014 It would be a great add-on to the app. Feel free to open a PR.
